name: open_meteo_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: 
  
dev_dependencies:
  build_runner: 
  mocktail: 
  test: 
  very_good_analysis:
