name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner:  
  coverage:  
  mocktail:  
  test: 
  very_good_analysis: 
